  - name: "show remote environment"
    shell: env

  - name: "copy backend binaries"
    become: true
    synchronize:
      src: ../../backend/dist
      dest: /home/ubuntu/uda_app
      recursive: true

  - name: "copy node_modules"
    become: true
    synchronize:
      src: ../../backend/node_modules
      dest: /home/ubuntu/uda_app
      recursive: true

  - name: "LIST"
    become: true
    command: ls
    ignore_errors: true

  - name: "delete anything that might already be running"
    become: true
    command: pm2 delete all
    ignore_errors: true


  - name: create systemd user dir
    file:
      path: /home/ubuntu/.config/systemd/user/
      state: directory

  - name: create bin user dir 
    file:
      path: /home/ubuntu/.bin
      state: directory
    
  - name: "add node autostart configuration."
    copy:
      src: uda_app.service
      dest: /home/ubuntu/.config/systemd/user/

  - name: "copy start script."
    copy:
      src: start.sh
      dest: /home/ubuntu/.bin
      mode: '0777'

  - name: "start uda_app service"
    systemd:
      daemon_reload: yes
      enabled: yes
      state: restarted 
      scope: user
      name: uda_app
    environment:
      ENVIRONMENT: production
      TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION') }}"
      TYPEORM_MIGRATIONS_DIR: "./migrations"
      TYPEORM_MIGRATIONS: "./migrations/*.js"
      TYPEORM_ENTITIES: "./modules/domain/**/*.entity{.ts,.js}"
      TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST') }}"
      TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_PORT') }}"
      TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME') }}"
      TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD') }}"
      TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE') }}"

